In [ ]:
x={"ram":'ram@manipal.edu',"bill gates":"billgates@mmanipal.edu"}
x["shyam"]="shyam@manipal.edu"
x

{'ram': 'ram@manipal.edu',
 'bill gates': 'billgates@mmanipal.edu',
 'shyam': 'shyam@manipal.edu'}

In [ ]:
for name in x:
  print(name)
  print(x[name])

ram
ram@manipal.edu
bill gates
billgates@mmanipal.edu
shyam
shyam@manipal.edu


In [ ]:
for email in x.values():
  print(email)

ram@manipal.edu
billgates@mmanipal.edu
shyam@manipal.edu


In [ ]:
for name in x:
  print(name)

ram
bill gates
shyam


In [ ]:
for name in x.items():
  print(name)

('ram', 'ram@manipal.edu')
('bill gates', 'billgates@mmanipal.edu')
('shyam', 'shyam@manipal.edu')


In [ ]:
for name1 in x:
  print(name1)

ram
bill gates
shyam


In [ ]:
for name,email in x.items():
  print(name)
  print(email)

ram
ram@manipal.edu
bill gates
billgates@mmanipal.edu
shyam
shyam@manipal.edu


In [ ]:
x=("Trisha","J","trishaj@gmail.com")
fname,lname,email=x

In [ ]:
Product,Name,Cost=("Milk","Sam",20)

In [ ]:
print(Product)
print(Name)
print(Cost)

Milk
Sam
20


In [ ]:
fname


'Trisha'

In [ ]:
lname

'J'

In [ ]:
email

'trishaj@gmail.com'

In [ ]:
sales_record={'price':3.42, 'num_items':4,'person':'Trisha','email':"trisha@gmail.com"}
sales_statement='{} bought {} item(s) at a price of INR {} each for total of INR {}'

print(sales_statement.format(sales_record['person'],sales_record['num_items'],sales_record['price'],sales_record['num_items']*sales_record['price']))

Trisha bought 4 item(s) at a price of INR 3.42 each for total of INR 13.68


In [ ]:
from datetime import date
from datetime import time
from datetime import datetime
import time


In [ ]:
tm=time.time()
tm

1696779272.3299577

In [ ]:
today=date.today()
today

datetime.date(2023, 10, 8)

In [ ]:
#Convert timestamp to datetime

dtnow=datetime.fromtimestamp(tm)
dtnow

datetime.datetime(2023, 10, 8, 15, 34, 32, 329958)

In [ ]:
dtnow.year,dtnow.month,dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2023, 10, 8, 15, 34, 32)

In [ ]:
#convert to days
delta=dt.timedelta(2)
type(delta)

datetime.timedelta

In [ ]:
import datetime as dt
today=dt.date.today()
print(today)
print(today-delta)

2023-10-08
2023-10-06


In [ ]:
today>today-delta

True

In [4]:
class Person:
  institute="Manipal School of Information Sciences"
  def set_name(self,new_name):
    self.name=new_name

  def set_location(self,new_location):
    self.location=new_location




In [5]:
person=Person()
person.set_name("Trisha")
person.set_location("Udupi")

In [7]:
print('{} lives in {} '.format(person.name,person.location))

Trisha lives in Udupi 


In [ ]:
z={1,'x',2,'y',3}
y={1,'x'}
print(z)
type(z)

{1, 2, 3, 'y', 'x'}


set

In [ ]:
y.add(4)
y

{1, 4, 'x'}

In [ ]:
store1=[10.00,11.00,12.34,5.34]
store2=[19.00,10.00,12.34,15.00]
store3=[15.00,12.00,11.00,6.00]
cheapest=list(map(min,store1,store2,store3))
costly=list(map(max,store1,store2,store3))
print(cheapest)
print(costly)

[10.0, 10.0, 11.0, 5.34]
[19.0, 12.0, 12.34, 15.0]


In [ ]:
for item in costly:
  print(item)

19.0
12.0
12.34
15.0


In [ ]:
def calculateSquare(n):
  return n*n

In [ ]:
numbers=(1,2,3,4)
result=map(calculateSquare,numbers)
print(type(result))
list(result)

<class 'map'>


[1, 4, 9, 16]

In [ ]:
for item in result:
  print(item)

In [ ]:
numbers=(1,2,3,4)
result=map(lambda x:x*x,numbers)
list(result)

[1, 4, 9, 16]

In [ ]:
type(result)

map

In [ ]:
num1=[4,5,6]
num2=[5,6,7]
result=map(lambda n1,n2:n1+n2,num1,num2)
print(list(result))
print(num1+num2)

[9, 11, 13]
[4, 5, 6, 5, 6, 7]


In [ ]:
person=['Python programming lang','computer lab','VINod scored A']
def split_title_name(person):
  title=person.split()[0]
  lastname=person.split()[-1]
  return '{} {}'.format(title,lastname)
list(map(split_title_name,person))



['Python lang', 'computer lab', 'VINod A']

In [ ]:
# -#return odd nos from 0 to 200
# def odd_nos(num):
#   for i in range(201):
list1=[i for i in range(0,201)if i%2!=0]
list1



[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199]

In [ ]:
#double each item in list using map
list1=[1,2,3]
double=map(lambda x:2*x,list1)
list(double)

[2, 4, 6]

In [ ]:
#lambda function takes 3 parameters and adds first



In [ ]:
import numpy as np

In [ ]:
mylist=[1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

In [ ]:
m=np.array([[1,2,3],[4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [ ]:
m.shape

(2, 3)

In [ ]:
#stop before 30
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
#9 equally spaced number
lspace=np.linspace(0,10,8)

lspace

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [ ]:
lspace.resize(2,4)
lspace

array([[ 0.        ,  1.42857143,  2.85714286,  4.28571429],
       [ 5.71428571,  7.14285714,  8.57142857, 10.        ]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
num=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
num

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
np.diag(num)

array([1, 5, 9])

In [ ]:
np.diag(num,1)

array([2, 6])

In [ ]:
np.diag(num,-1)[0]

4

In [ ]:
p1=np.ones([2,3],int)
p=np.zeros((3,2))
p1

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.hstack([p,2*p])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
p

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [ ]:
np.vstack([b,a,a])

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6]])